### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by mildred**
Specifically, explain how portal implementations are chosen and provide the path to where the configuration files are located. Link to useful tools to debug portals.

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
Thanks. As clarified on Matrix, this is probably better as a documentation page after https://github.com/flatpak/xdg-desktop-portal/pull/1157 lands.

**Comment by GeorgesStavracas** [comment]
#1157 landed, please make this a documentation page :)

**Comment by swick** [comment]
All of this information is already available in `system-integration.rst` and `portals.conf.rst.in`

**Comment by GeorgesStavracas** [comment]
> I wonder if we should reduce the scope of the readme and link more extensively to the website instead.

I think that would be good, I don't particularly enjoy duplicating too much between the docs website and README.

**Comment by GeorgesStavracas** [comment]
Okay let's close this then, thanks for verifying this swick

**Pull request closed without merging**
