### PR TITLE
WIP: settings: Support backend implementation

### PR DESCRIPTION
**Pull request by TingPing**
I have not tested this with an actual backend but this should be the general idea.

Do not merge until tested.

CC @grulja

### CODE REVIEW

**Comment by matthiasclasen** [comment]
Looks good to me, modulo testing.

**Comment by grulja** [comment]
There is a typo in the signal name. The introspection file says it is "SettingChanged", while you are trying to connect to "SettingsChanged", actually in the code it is "settings-changed" because of the auto-generated code. I will report other issues (if any) once I proceed next with my backend implementation.

**Comment by grulja** [comment]
Update:
Now when returning my results, I get following error:
g_variant_builder_add_value: assertion '!GVSB(builder)->expected_type || g_variant_is_of_type (value, GVSB(builder)->expected_type)' failed

**Comment by TingPing** [comment]
@grulja All issues should have been fixed now.

**Comment by grulja** [comment]
Still doesn't seem to work correctly, when I return more than one namespace with their properties, it adds just the first one to the resulting map. I see a long list of namespaces I returned when watching it using dbus-monitor so it is definitely correct on my side.

**Pull request merged**
