### PR TITLE
docs: Document Since for FileChooser

### PR DESCRIPTION
**Pull request by A6GibKm**
These options were added since version 3 of this interface.

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
Why are you bumping the interface version to 4?

**Comment by A6GibKm** [comment]
Because they are new methods.

**Comment by GeorgesStavracas** [comment]
Please document it in the commit message in details then

**Comment by A6GibKm** [comment]
Done.

**Review by GeorgesStavracas — APPROVED** [review]

**Pull request merged**
