### PR TITLE
dynamic-launcher: Make desktop file executable

### PR DESCRIPTION
**Pull request by JakobDev**
The dynamics launcher portal is currently not working under KDE, as KDE requires desktop files to be executable for some reason. This fixes it.

### CODE REVIEW

**Comment by davidedmundson** [comment]
>as KDE requires desktop files to be executable for some reason

That's not a completely true story, it shouldn't apply for installed applications, and at most it gives a prompt.

>The dynamics launcher portal is currently not working under KDE,

Can you expand on this please.

**Comment by GeorgesStavracas** [comment]
Changed to draft so nobody accidentally merges it

**Comment by Sodivad** [comment]
Hi this prompt/failure was due to not accounting for desktop files linked into the applications directory
Fixed via https://invent.kde.org/frameworks/kconfig/-/commit/6772deba4c2682f1faf8967ba8200db48528f2b2

**Comment by GeorgesStavracas** [comment]
Given the last comment, I'll close this PR. Thanks for looking at it on the KDE side!

**Pull request closed without merging**
