### PR TITLE
[WIP, don't merge yet] Add support for PipeWire 0.3

### PR DESCRIPTION
**Pull request by grulja**

### CODE REVIEW

**Comment by grulja** [comment]
PipeWire 0.3 is not released yet, but once it is released, the library will be called libpipewire-03 and there are some API changes. I don't want this to be merged yet, as there might be some other changes needed until PW 0.3 is released. This at least makes this change visible to others who might wan to try upcoming PW version.

**Comment by matthiasclasen** [comment]
Is this still relevant ?

**Comment by grulja** [comment]
I guess this or a similar change will be needed when PW 0.3 is out, but I haven't been folowing its development for a while.

**Comment by danshick** [comment]
Not sure what commit https://github.com/PipeWire/pipewire/issues/158#issuecomment-535855558 is in reference to, but I think this broke this PR.

**Comment by grulja** [comment]
Closing because of https://github.com/flatpak/xdg-desktop-portal/pull/436. This change is outdated and doesn't reflect current PipeWire API.

**Pull request closed without merging**
