### PR TITLE
build: Drop Autotools

### PR DESCRIPTION
**Pull request by ebassi**
None of the supported versions and platforms requires Autotools, so we can drop it from the build and from the CI pipeline.

### CODE REVIEW

**Comment by ebassi** [comment]
This should be merged after branching the main development branch, so we can keep Autotools for 1.16.

**Comment by GeorgesStavracas** [comment]
I removed the requirement for Ubuntu 16.04 so we can eventually land this. After landing, we can bring back the required CI flows.

**Comment by GeorgesStavracas** [comment]
(To be clearer, I have not reviewed this yet)

**Comment by smcv** [comment]
> I removed the requirement for Ubuntu 16.04 so we can eventually land this

Ubuntu 16.04 is EOL for everything except subscription-based updates, so I think it's reasonable to say that Ubuntu 16.04 users should have no expectation of being able to run the latest x-d-p.

**Comment by GeorgesStavracas** [comment]
I'm pretty sure we can drop a bunch of GLib compatibility code that we copied in-tree too

**Comment by ebassi** [comment]
Yeah, I wanted to drop the compatibility code in a separate MR.

**Comment by GeorgesStavracas** [comment]
Sounds good!

**Review by GeorgesStavracas — APPROVED** [review]

**Pull request merged**
