### PR TITLE
print: Add "supported_output_file_formats" option

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
This allows applications tell portal backends which file formats they
support. In turn, portal backends can then limit the choices presented
to the user.

### CODE REVIEW

**Review by TingPing — APPROVED** [review]
Seems very reasonable to me.

**Comment by matthiasclasen** [comment]
I assume this will need a corresponding gtk change to say that we only do pdf ?

**Comment by matthiasclasen** [comment]
Looks fine to me too

**Comment by GeorgesStavracas** [comment]
> I assume this will need a corresponding gtk change to say that we only do pdf ?

No. I actually thought so, and started looking at GtkPrintOperation - but realized soon enough that, actually, GtkPrintOperation is good and respect the output file format, it uses cairo-pdf for PDF, cairo-ps for PostScript, and plain cairo for SVG.

**Comment by grulja** [comment]
I think this is fine from Qt POV, my understanding is that it can only print to PDF.

**Pull request merged**
