### PR TITLE
Update LINGUAS - added sl (Slovenian)

### PR DESCRIPTION
**Pull request by filmsi**
Added support for Slovenian language.

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
Almost! This PR also needs to include the file `po/sl.po`. You can do that with:

```
$ git add po/sl.po
$ git commit --amend --no-edit
$ git push --force-with-ease
```

**Comment by filmsi** [comment]
I don't know how to do it.
I do not use git on my computer.

**Comment by filmsi** [comment]
I created sl.po in another commit.
To both projects.

**Comment by GeorgesStavracas** [comment]
It's okay. I can merge them in reverse order. Thanks for the pull requests.

**Pull request merged**
