### PR TITLE
Update zh_TW.po translation

### PR DESCRIPTION
**Pull request by gostsdmitry**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Why did you remove the LINGUAS file? This is not correct.

**Comment by gostsdmitry** [comment]
> Why did you remove the LINGUAS file? This is not correct.

https://github.com/gostsdmitry/xdg-desktop-portal/blob/master/po/LINGUAS

**Comment by gostsdmitry** [comment]
Is everything correct now?

**Comment by AsciiWolf** [comment]
It is not -"hi" should not be added to the LINGUAS file, Hindi translation is not a part of this PR.

**Comment by gostsdmitry** [comment]
> It is not -"hi" should not be added to the LINGUAS file, Hindi translation is not a part of this PR.

https://github.com/flatpak/xdg-desktop-portal/blob/master/po/LINGUAS

**Comment by gostsdmitry** [comment]
I have finished executing a pull request. Please someone review my changes and take a decision on them.

**Comment by matthiasclasen** [comment]
Can you rebase this on master to get rid of the conflicts ?

**Comment by AsciiWolf** [comment]
LGTM now, thanks!

**Comment by gostsdmitry** [comment]
The translation process into Traditional Chinese has been completed.

**Pull request merged**
