### PR TITLE
org.freedesktop.portal.Notification: clarify icon validation requirem…

### PR DESCRIPTION
**Pull request by whereswaldon**
…ents

### CODE REVIEW

**Comment by matthiasclasen** [comment]
+1 from me

**Comment by swick** [comment]
Could be exhaustive:
```
    .name = "notification",
    .max_icon_size = 512,
    .max_svg_icon_size = 4096,
    .max_file_size = 1024 * 1024 * 4 /* 4MB */,
```

so file size limit for svg 4k, raster 4mb.

**Comment by GeorgesStavracas** [comment]
I appreciate the documentation improvement, but I think this should be a separate doc page containing some sort of table, or exhaustive list of criteria. Then this page can be referenced from various D-Bus files.

**Comment by whereswaldon** [comment]
I've done my best to move this to a new page with a table of requirements. Feel free to tweak the content to reflect whatever the preferred verbiage is.

**Review by GeorgesStavracas — APPROVED** [review]

**Comment by swick** [comment]
What's still kind of problematic is the fact that the file types that are supported depends on the gdk pixbuf backends which are available to the portal. You can do all the "right" things regarding file size, dimensions etc and still get your icon rejected.

**Pull request merged**
