### PR TITLE
Settings portal: Date and Time formats

### PR DESCRIPTION
**Pull request by orowith2os**
This is my proposal for new settings under the Settings portal. I got the idea from Android, and it should help with a tiny bit more consistency in apps and desktops.

### CODE REVIEW

**Comment by orowith2os** [comment]
I'll be completely honest, everything about time and date here on Linux is weird, so I might not fully understand all this, but it's an idea. I was also curious about seeing if a time zone preference is necessary, for apps to do calculations with?

**Comment by swick** [comment]
-> discussions

**Comment by jadahl** [comment]
> -> discussions

Can't turn pull requests into discussions.

With that said, 12/24h etc is already handled via `LC_TIME`. For example, run `flatpak run --command=sh some.flatpak.App` and then `locale` inside.

**Comment by orowith2os** [comment]
Ah. Sorry, then.

**Comment by swick** [comment]
Yeah, might be nice to have a portal for this but I guess you first have to convince toolkits.

**Comment by orowith2os** [comment]
Maybe if a portal like this gets the go-ahead, we can just add *all* the `LC_*` variables? Thoughts?

**Pull request closed without merging**
