### PR TITLE
global-shortcuts: Emit signals to session correctly

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
The appropriate object path is the session's object path, represented by its id.

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
@whot @jadahl something that would be good to figure out, is why the Python test didn't catch this, and how can it be adapted to test for this issue?

**Comment by GeorgesStavracas** [comment]
Welp, that explains it - the Python test is apparently testing the wrong behaviour (or at least, as far as I understood, this is the wrong behaviour...)

**Comment by whot** [comment]
I can't find where I discussed this with @jadahl but this behaviour seems to be correct, it's a legacy of the portal that things happen not on the session object itself but always on the xdg-desktop-portal object. The session only ever has `Close`, all other signals are sent on the portal but have the session handle as argument.

Switching this will break things because everything else expects the signals to happen on the main portal object.

Oh, and the `Session` shouldn't even have that interface.

**Comment by jadahl** [comment]
It's a legacy that e.g. the remote desktop isn't also a an interface on the session, because one first creates the session, and only later associates "things" with it (e.g. remote desktop, screen cast, clipboard).

The session itself is still a D-Bus object on some path, since it has a method (`Close()`), so with that in mind, the sane thing would be that the `Closed` signal happens on that object as well.

**Comment by jadahl** [comment]
I was confusing myself, I somehow thought this was about the `org.freedesktop.Session.Closed` signal. In the case of `GlobalShortcuts` and any other signal that is similar to it, the signal must be emitted on the same object that the interface is on, meaning `/org/freedesktop/porta/desktop`.

**Pull request closed without merging**
