### PR TITLE
Disable broken test

### PR DESCRIPTION
**Pull request by hfiguiere**
This test require unreleased code in a dependency. This fixes the build

### CODE REVIEW

**Comment by hfiguiere** [comment]
see https://github.com/flatpak/xdg-desktop-portal/pull/1479#discussion_r1808664882

**Comment by swick** [comment]
I don't see why this would be necessary when we can just pull in the required libportal commit.

**Comment by hfiguiere** [comment]
because the commit doesn't exist in the libportal repository yet. If you really want to do that, get it merged.

Using a fork is NOT a solution. It's another breakage in the making.

**Comment by swick** [comment]
It works, so it is a solution.

**Comment by hfiguiere** [comment]
It is fragile - what happen when the fork disappear? And it blocks any upgrade to libportal - aka it blocks other contributions. So it makes it worse.

**Comment by swick** [comment]
Alright, let's go with this one.

**Comment by swick** [comment]
As for why CI didn't notice: libportal is missing from the image. https://github.com/flatpak/xdg-desktop-portal/pull/1479 fixes that.

**Comment by swick** [comment]
Had to ifdef out a few more things to get tests passing on current libportal main: https://github.com/flatpak/xdg-desktop-portal/pull/1479/commits/ebb8d907a2e39ef78aff17bd0e793db058c0c0ab

**Comment by hfiguiere** [comment]
Updated the patch. Test passes.

**Comment by swick** [comment]
LGTM

**Comment by hfiguiere** [comment]
btw just ICYMI, I don't have permissions to merge, so someone needs to do this.

**Review by GeorgesStavracas — APPROVED** [review]

**Pull request merged**
