### PR TITLE
Clarify the docs on filters in the file chooser

### PR DESCRIPTION
**Pull request by matthiasclasen**
Make it explicit that patterns are case-sensitive.

Closes https://github.com/flatpak/xdg-desktop-portal/issues/225

### CODE REVIEW

**Comment by mcatanzaro** [comment]
LGTM

**Comment by matthiasclasen** [comment]
We were discussing changing gtk to be case insensitive, but no change has been merged yet, which is why this is still open

**Comment by mcatanzaro** [comment]
For the record, that's https://gitlab.gnome.org/GNOME/gtk/merge_requests/359

**Comment by hadess** [comment]
I'm guessing the plan would be to offer a way to make matches case insensitive?

**Comment by matthiasclasen** [comment]
We've  added GtkFileFilter api to create case-insensitive filters, using suffix matches. Those will be translated into case-insensitive patterns for the native (portal) filechooser.

**Pull request merged**
